require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'app/controllers/line_bot_controller.rb'
    - 'config/application.rb'
  DisplayCopNames: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  CountComments: false
  Max: 30
  Exclude:
    - 'app/models/user.rb'


Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 40

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
