require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'app/controllers/line_bot_controller.rb'
  DisplayCopNames: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Max: 25
#   Exclude:
#     - 'app/controllers/line_bot_controller.rb'

# Metrics/CyclomaticComplexity:
#   Exclude:
#     - 'app/controllers/line_bot_controller.rb'

# Metrics/MethodLength:
#   Exclude:
#     - 'app/controllers/line_bot_controller.rb'

# Metrics/PerceivedComplexity:
#   Exclude:
#     - 'app/controllers/line_bot_controller.rb'


# Metrics/CyclomaticComplexity:
#   Max: 30

Metrics/MethodLength:
  CountComments: false
  Max: 30
  Exclude:
    - 'app/models/user.rb'


Metrics/ClassLength:
  Max: 200

# Naming/AccessorMethodName:
#   Exclude:
#     - 'app/controllers/**/*'

Style/AsciiComments:
  Enabled: false

# Style/BlockDelimiters:
#   Exclude:
#     - 'spec/**/*_spec.rb'

# Style/Documentation:
#   Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# クラスにコメントを残さない
Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

# Metrics/BlockNesting:
#   Max: 5